services:
  mysql:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: taskmanager
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  nodejs:
    image: node:20-alpine
    ports:
      - "5173:5173"  # Updated port
    volumes:
      - ./vite/:/app/
    command: sh -c "cd /app/ && npm i && npm run dev"
    expose: [5173]
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=taskmanager
    depends_on:
      - mysql
      - rabbitmq

  golang:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Updated port
    depends_on:
      - mysql
      - rabbitmq
      
  websocket:
    build:
      context: ./websocket-server # Path to the WebSocket server directory
    ports:
      - "8080:8080"
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

volumes:
  mysql-data:
